<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_PackML_PushButtonControl" Id="{6be5865f-6c78-4181-b3c0-db233d854256}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PackML_PushButtonControl EXTENDS FB_PackML_ExternalControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bStartButton	AT %I* : BOOL;	//Tie to hardware start pushbutton
	//TODO: add other buttons
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//TODO: implement button control]]></ST>
    </Implementation>
    <LineIds Name="FB_PackML_PushButtonControl">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>