<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_Cylinder_DualSolenoid_DualSensor" Id="{54913be8-2f9a-4c62-91f9-7183be15cd2e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Cylinder_DualSolenoid_DualSensor EXTENDS FB_Cylinder_DualSensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bExtend_Actuator_HardwareOutput 	AT %Q* 	: BOOL;
	bRetract_Actuator_HardwareOutput 	AT %Q* 	: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="01_SUPER_Overrides" Id="{b1091b7f-7b7c-40ae-923e-78fa7db5ad15}" />
    <Method Name="HardwareUpdate" Id="{1a62f8fc-8df7-4ab8-a437-e384e4ffc47d}" FolderPath="01_SUPER_Overrides\">
      <Declaration><![CDATA[METHOD HardwareUpdate : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.HardwareUpdate();

bExtend_Actuator_HardwareOutput := bExtendCommand;
bRetract_Actuator_HardwareOutput := bRetractCommand;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Cylinder_DualSolenoid_DualSensor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Cylinder_DualSolenoid_DualSensor.HardwareUpdate">
      <LineId Id="11" Count="1" />
      <LineId Id="10" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>