<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_Cylinder_DualSensor" Id="{548cb264-8e0d-49f7-a008-32e71d85168c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Cylinder_DualSensor EXTENDS FB_CylinderBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbSensor_Extended							: FB_Sensor;
	fbSensor_Retracted							: FB_Sensor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="01_SUPER_Overrides" Id="{4dc883f4-4cfb-47b5-86e5-2bb7b1d9b438}" />
    <Method Name="HardwareUpdate" Id="{692e3844-c464-4955-a750-d8f7a26ca635}" FolderPath="01_SUPER_Overrides\">
      <Declaration><![CDATA[METHOD HardwareUpdate : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbSensor_Extended.CyclicLogic();
fbSensor_Retracted.CyclicLogic();

bExtendedFeedback:= fbSensor_Extended.Active;
bRetractedFeedback := fbSensor_Retracted.Active;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Cylinder_DualSensor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Cylinder_DualSensor.HardwareUpdate">
      <LineId Id="6" Count="3" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>