<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_Sensor" Id="{600a0be8-8f86-40d7-91ca-048d45e1e72d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Sensor EXTENDS FB_SensorBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bSensor_HardwareInput	AT %I* : BOOL;	//Hardware input bit from the hysical sensor
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="01_SUPER_Overrides" Id="{0678f6d0-782c-4a6f-9d10-9b0a34b9542e}" />
    <Method Name="HardwareUpdate" Id="{10f795a8-9ec4-4b2a-8124-c7a53d3ba7ea}" FolderPath="01_SUPER_Overrides\">
      <Declaration><![CDATA[METHOD PRIVATE HardwareUpdate : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.HardwareUpdate();

bRawSensorInput := bSensor_HardwareInput;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Sensor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Sensor.HardwareUpdate">
      <LineId Id="9" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>